spring:
  application:
    name: qr-service

server:
  port: ${SERVER.PORT}
  ssl:
    key-store: ${SSL.KEY.STORE}
    key-store-password: ${SSL.KEY.STORE.PASSWORD}
    key-store-type: ${SSL.KEY.STORE.TYPE}
    key-alias: ${SSL.KEY.ALIAS}